document_analysis_task:
  description: >
    Analyze the provided resume using PDF tool. Extract and summarize all critical information, including work experience, skills, education, and key achievements.
    Present the output as a clean, well-structured text summary. Do not use JSON.
  agent: document_analyzer
  expected_output: |
    A clean, well-formatted text summary of the resume's content. Example:

    **Personal Details**
    - Name: [Full Name]
    - Email: [Email Address]
    - Phone: [Phone Number]
    - LinkedIn: [LinkedIn Profile URL]
    - Location: [City, Country]

    **Summary**
    [Candidate's professional summary or objective]

    **Work Experience**
    - **[Job Title]** at [Company Name] | [Location] | [Start Date] - [End Date]
      - [Responsibility or achievement 1]
      - [Responsibility or achievement 2]
    - **[Previous Job Title]** at [Previous Company Name] | [Location] | [Start Date] - [End Date]
      - [Responsibility or achievement 1]

    **Education**
    - **[Degree]** in [Field of Study] - [University Name], [Location] ([Graduation Year])
      - Relevant Coursework: [List of relevant courses]

    **Skills**
    - Technical: [List of technical skills, e.g., Python, SQL, SAP]
    - Languages: [List of languages and proficiency, e.g., English (C1), French (B2)]
    - Certifications: [List of relevant certifications]

    **Projects**
    - **[Project Name]** ([Year])
      - [Brief project description and technologies used]

candidate_matching_task:
  description: >
    Apply the scoring matrix with ABSOLUTE consistency. Follow the evidence classification rules exactly.
    Use the mandatory scoring algorithm without any deviation.
    
    CRITICAL: For each skill in {barem}, you MUST:
    1. Quote the exact evidence from resume
    2. State which classification it falls under (and why)
    3. Apply the corresponding score from the matrix
    4. Show the calculation: (score/5) * weight
    
  agent: matching_specialist
  expected_output: |
    **DETERMINISTIC SCORING ANALYSIS**
    
    **Final Score:** [X.X]/10
    
    **DETAILED BREAKDOWN:**
    
    ### [Skill Name] (Weight: [X])
    **Evidence:** "[Exact quote from resume]"
    **Classification:** [Matrix category] - [Brief justification]
    **Score:** [X]/5
    **Calculation:** ([X]/5) * [weight] = [result]
    
    ### [Next Skill]...
    
    **TOTAL CALCULATION:**
    Sum of weighted scores: [sum]
    Final normalized score: [sum]/10 = [final score]


report_generation_task:
  description: >
    Generate a comprehensive and actionable hiring report in markdown format using the analysis from the previous step.
    The report must include detailed strengths analysis, comprehensive gaps assessment, and strategic next steps for the hiring process.
    Focus on providing actionable insights and specific interview guidance.
  agent: report_generator
  expected_output: |
    # Candidate Evaluation Report
    
    **Candidate:** [Candidate Name]
    **Position:** [Job Title]
    **Evaluation Date:** [Current Date]
    **Overall Score:** [X.X]/10
    
    ## Executive Summary
    [2-3 sentence summary of the candidate's overall fit, highlighting key strengths and main concerns]
    
    ## Detailed Scoring Breakdown
    [Include the detailed scoring analysis from matching_specialist]
    
    ## ✅ Strengths Analysis
    
    ### Strong Technical Competencies
    - **[Skill Name]** ([Score]/5): [Detailed explanation of evidence found, specific examples from resume, and why this is valuable for the role]
    - **[Skill Name]** ([Score]/5): [Detailed explanation with context of how this skill was demonstrated]
    
    ### Notable Experience Highlights
    - **[Experience/Achievement]**: [Detailed explanation of why this experience is relevant and valuable]
    - **[Experience/Achievement]**: [Context and potential impact for the target role]
    
    ### Transferable Skills & Potential
    - [List skills that may not be exact matches but show strong potential for growth]
    - [Highlight learning agility, adaptability, or foundational knowledge that could be built upon]
    
    ## ❌ Critical Gaps Analysis
    
    ### High-Priority Missing Skills
    - **[Skill Name]** (Weight: [X]%): 
      - **Impact:** [High/Medium/Low] - [Explanation of how this gap affects job performance]
      - **Mitigation:** [Training potential, timeline, or alternative solutions]
      - **Risk Level:** [Assessment of risk if candidate is hired without this skill]
    
    ### Secondary Skill Gaps
    - **[Skill Name]** (Weight: [X]%): [Shorter assessment of gap and potential solutions]
    
    ### Experience Gaps
    - [Industry-specific experience missing]
    - [Role-level experience considerations]
    - [Team size, project complexity, or domain expertise gaps]
    
    ## 📋 Next Steps & Interview Strategy
    
    ### Recommended Interview Approach
    **Interview Type:** [Phone Screen/Technical Interview/Panel Interview/Behavioral Interview]
    **Duration:** [Recommended time allocation]
    **Focus Areas:** [Primary areas to explore based on gaps and strengths]
    
    ### Technical Assessment Recommendations
    - **[Skill to Assess]**: [Specific exercise or question type]
    - **[Skill to Assess]**: [Practical test or scenario-based assessment]
    - **[Skill to Assess]**: [Portfolio review or code sample analysis]
    
    ### Targeted Interview Questions
    
    #### Technical Competency Questions
    - **[High-Priority Skill]**: 
      - "Can you walk me through a specific project where you used [skill]? What were the challenges and how did you overcome them?"
      - "How would you approach [specific scenario related to the skill]?"
    
    - **[Gap Area to Explore]**:
      - "How familiar are you with [missing skill]? Have you had any exposure to it?"
      - "How do you typically approach learning new [technical skill type]?"
    
    #### Experience & Situational Questions
    - "Describe a time when you had to [relevant scenario based on job requirements]"
    - "How do you handle [specific challenge relevant to the role]?"
    - "Tell me about your experience with [industry/domain specific context]"
    
    #### Learning & Growth Questions
    - "How do you stay updated with [relevant technology/industry trends]?"
    - "Describe a time when you had to quickly learn a new skill for a project"
    - "What areas are you most interested in developing professionally?"
    
    ### Reference Check Focus Areas
    - Verify technical competencies in [specific high-weight skills]
    - Assess performance in [areas where gaps were identified]
    - Understand learning agility and adaptation to new technologies/processes
    